feat: add a maintainer guide for jenkins x
jenkins-x/jx-docs pull request #3581
Opened 2022-03-31 12:12 UTC by ankitm123

# Description

We dont have a maintainer guide, this is an attempt at adding one.
Hopefully, we will make it better with time.

Fixes # (issue)

# Checklist:

- [ ] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [ ] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [ ] Any dependent changes have already been merged.

2022-05-09 17:43 UTC, ankitm123 commented
/hold

2022-05-09 17:44 UTC, ankitm123 commented
/hold

2022-05-09 17:45 UTC, ankitm123 commented
/hold cancel

2022-05-09 17:46 UTC, ankitm123 commented
/hold

2022-05-09 17:51 UTC, ankitm123 commented
/hold cancel

2022-05-13 12:36 UTC, ankitm123 commented
/test pr

2022-05-14 17:18 UTC, ankitm123 commented
/test pr

2022-05-21 16:37 UTC, ankitm123 commented
/retest

2022-07-07 15:07 UTC, tomhobson requested changes

2022-07-07 15:07 UTC, tomhobson commented on content/en/community/maintainer_guide/infrastructure.md
> +Test clusters are created here when a pull request is opened in the [jx3-versions](https://github.com/jenkins-x/jx3-versions) repository.
should we mention the gc things here?

2022-07-07 15:10 UTC, babadofar commented on content/en/community/maintainer_guide/mentorship/_index.md
> +
"and to onboard new contributors"

2022-07-07 15:37 UTC, ankitm123 commented on content/en/community/maintainer_guide/infrastructure.md
> +Test clusters are created here when a pull request is opened in the [jx3-versions](https://github.com/jenkins-x/jx3-versions) repository.
Done

2022-07-07 15:37 UTC, ankitm123 commented on content/en/community/maintainer_guide/mentorship/_index.md
> +
Done.

2022-07-07 15:50 UTC, tomhobson approved these changes

2022-07-07 15:51 UTC, merged